events {}

http {
  access_log off;
  error_log /dev/stderr warn;

  server {
    listen 8081;

    location / {
      proxy_pass http://dev-center:8080;
      proxy_set_header Host resource.casa;
      proxy_pass_request_headers on;
    }
  }
}
